name: test with report coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt pytest-cov
  
      - name: Run tests and generate coverage report
        run: |          
          python -m pytest --cov-report xml:coverage.xml --cov=src tests/

      - name: Comment coverage report
        uses: MishaKav/pytest-coverage-comment@v1.1.48
        with:
          pytest-coverage-path: coverage.xml
         
